function shuffle(arr: string[]) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

export class Word {
  arr: string[];

  constructor() {
    this.arr = [
      "are",
      "all",
      "against",
      "at",
      "become",
      "could",
      "do",
      "while",
      "when",
      "how",
      "however",
      "would",
      "right",
      "mountain",
      "might",
      "through",
      "whether",
      "quote",
      "fountain",
      "will",
      "rain",
      "time",
      "day",
      "night",
      "light",
      "dark",
      "tree",
      "green",
      "fast",
      "slow",
      "jump",
      "run",
      "blue",
      "red",
      "yellow",
      "pink",
      "black",
      "white",
      "stone",
      "river",
      "water",
      "fire",
      "wind",
      "cloud",
      "sky",
      "above",
      "below",
      "inside",
      "outside",
      "before",
      "after",
      "begin",
      "end",
      "open",
      "close",
      "look",
      "see",
      "feel",
      "touch",
      "hear",
      "think",
      "know",
      "love",
      "hate",
      "give",
      "take",
      "bring",
      "carry",
      "stand",
      "sit",
      "walk",
      "talk",
      "listen",
      "write",
      "read",
      "type",
      "learn",
      "teach",
      "build",
      "break",
      "start",
      "stop",
      "find",
      "lose",
      "make",
      "create",
      "destroy",
      "trust",
      "doubt",
      "reach",
      "climb",
      "fall",
      "fly",
      "dream",
      "hope",
      "smile",
      "laugh",
      "cry",
      "help",
    ];
  }

  usemyarray() {
    shuffle(this.arr);
  }
}
